# Generated by Django 4.2.4 on 2023-08-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksYear1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Book_images/')),
                ('author', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=200)),
                ('edition', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
            ],
        ),
    ]
