# Generated by Django 4.2.4 on 2023-08-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0002_booksyear1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksyear1',
            name='image',
        ),
    ]
